### ISSUE TITLE
Is this the final version of the code?

### ISSUE THREAD

**Issue by JackWoo0831** [cilinyan/VISA#2]
Hi there! Many thanks for your excellent work!

May I ask is the final version of the code? Because I cannot find the code corresponding to `Text-guided Frame Sampler.` Also, it seems that the tracking part is missing.

Looking forward for your reply!

**Comment by cilinyan** [comment]
Indeed, the current version of the code available on the repository is not the final one. We are still in the process of refining and organizing the remaining components.

Regarding your query, the current code partially implements Local Sampling within the Text-guided Frame Sampler (TFS). Here's how it works:

1. For each frame in the video, we [uniformly sample 12 adjacent frames](https://github.com/cilinyan/VISA/blob/main/utils/rvos_eval_dataset.py#L64) as reference frames for inference. You can execute this implementation by running the [val_7b_video.sh](https://github.com/cilinyan/VISA/blob/main/scripts/val_7b_video.sh).
2. We employ LLaMA-VID to select the target frame based on the guidance text, which is detailed in [utils_llamavid](https://github.com/cilinyan/VISA/tree/main/utils_llamavid).
3. Acknowledged, the feature for propagating the target frame mask across the video using XMem is currently missing. We will expedite its release. Thank you for your patience.

Please stay tuned for updates, as we are committed to enhancing the codebase and ensuring all features are comprehensively covered.

Best regards.

**Comment by JackWoo0831** [comment]
Many thanks for your thorough reply. I did not read the code very carefully haha, the target frames are preprocessed before training process. I see! I have starred this repo for a little support 😆

**Comment by cilinyan** [comment]
We have uploaded the code for XMem.
