### ISSUE TITLE
The data preparation of RefYoutube-VOS and Davis2017

### ISSUE THREAD

**Issue by SitongGong** [cilinyan/VISA#3]
Thank you for your wonderful job! 
After I downloaded the dataset and ran the training code, I met a small question: The RefYoutube-VOS and the DAVIS dataset don't include the mask_dict.json file, their masks are annotated as gray images. So do I need to transfer the annotations into the mask_dict.json file, or do you have the transformation code, thank you for your reply!

**Comment by cilinyan** [comment]
[download link](https://github.com/cilinyan/VISA/blob/046abaa02d5052666272c37a96e40a1be8e65744/README.md?plain=1#L74-L76) 😆
